FROM public.ecr.aws/lambda/python:3.12 AS build

WORKDIR /app
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt


FROM public.ecr.aws/lambda/python:3.12

WORKDIR /app

COPY --from=build /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=build /usr/local/bin /usr/local/bin

COPY . .


CMD ["lambda_handler.lambda_handler"]
